# Generated by Django 3.1.7 on 2022-01-09 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220109_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
